### ISSUE TITLE
建议将TLCP_ECC_SM4_GCM_SM3优先于TLCP_ECC_SM4_CBC_SM3

### ISSUE THREAD

**Issue by emmansun** [Trisia/gotlcp#1]
总体来说GCM模式比CBC模式安全。另外从实现性能来讲，GCM模式加解密可以并行，CBC模式只有解密可以并行，当然这取决于SM4_CBC 、 SM4_GCM具体实现。

**Comment by Trisia** [comment]
以于 v1.0.5 优先使用 ECC_SM4_GCM_SM3 算法套件
