### ISSUE TITLE
[sync sdk] tls: use certificate cache in client

### ISSUE THREAD

**Issue by emmansun** [Trisia/gotlcp#11]
In verifyServerCertificate parse certificates using the global certificate cache.

This should significantly reduce memory usage in TLS clients which make concurrent connections which reuse certificates (anywhere in the chain) since there will only ever be one copy of the certificate at once.

**Comment by Trisia** [comment]
简单来说也在客户端侧，针对同一个服务端的所有连接，仅进行一次证书的解析是这样吧？

我看了Go官方确实提供了一个缓存器

https://github.com/golang/go/blob/205f636e0ab491b7a06e7b7879abb897cdaaf1b4/src/crypto/tls/handshake_client.go#L855


我先看下工作原理，若合适确实可以考虑进行同步

**Comment by emmansun** [comment]
https://github.com/golang/go/issues/46035

**Comment by Trisia** [comment]
我看了下确实没有什么问题，问题有所顾虑就是超时时间问题，我看它也是用`runtime.SetFinalizer` 对证书进行回收，确实是比较优秀的设计，预计于 v1.2.4 增该特性

https://github.com/golang/go/blob/205f636e0ab491b7a06e7b7879abb897cdaaf1b4/src/crypto/tls/cache.go
