### ISSUE TITLE
RequireAndVerifyClientCert error

### ISSUE THREAD

**Issue by pedroalbanese** [Trisia/gotlcp#12]
Greetings!

I'm trying to configure TLCP to work like standard TLS, with just one key and one certificate for each side. It happens that I get an error message referring to cipher suites: "server: handshake failed: tlcp: no cipher suite supported by both client and server".

Can anyone point me out what's wrong with my code please?

```go
package main

import (
	"bufio"
	"bytes"
	"crypto/rand"
	"encoding/pem"
	"errors"
	"flag"
	"fmt"
	"log"
	"net"
	"os"

	"gitee.com/Trisia/gotlcp/tlcp"
	"github.com/emmansun/gmsm/smx509"
)
var (
	cert      = flag.String("cert", "Certificate.pem", "Certificate path.")
	tcpip     = flag.String("tcp", "", "Encrypted TCP Transfer Protocol. [server|client]")
	key       = flag.String("key", "", "`Private key.")
	iport     = flag.String("ipport", "", "Local Port/remote's side Public IP:Port.")
)

func handleConnection(c net.Conn) {
	log.Printf("Client(TLS) %v connected via secure channel.", c.RemoteAddr())
}

func main() {
	flag.Parse()
	if (*tcpip == "server" || *tcpip == "client") {
		var certPEM []byte 
		var privPEM []byte

		file, err := os.Open(*key)
		if err != nil {
			log.Fatal(err)
		}
		info, err := file.Stat()
		if err != nil {
			log.Fatal(err)
		}
		buf := make([]byte, info.Size())
		file.Read(buf)

		var block *pem.Block
		block, _ = pem.Decode(buf)

		if block == nil {
			errors.New("no valid private key found")
		}

		privPEM = buf

		file, err = os.Open(*cert)
		if err != nil {
			log.Fatal(err)
		}
		info, err = file.Stat()
		if err != nil {
			log.Fatal(err)
		}
		buf = make([]byte, info.Size())
		file.Read(buf)
		certPEM = buf

		if *tcpip == "server" {
			var cert tlcp.Certificate
 			cert, err = tlcp.X509KeyPair(certPEM, privPEM)
			cfg := tlcp.Config{Certificates: []tlcp.Certificate{cert, cert}, CipherSuites: []uint16{tlcp.ECC_SM4_GCM_SM3}, ClientAuth: tlcp.RequireAndVerifyClientCert}
			cfg.Rand = rand.Reader

			port := "8081"
			if *iport != "" {
				port = *iport
			}

			ln, err := tlcp.Listen("tcp", ":"+port, &cfg)
			if err != nil {
				log.Fatal(err)
			}

			fmt.Fprintln(os.Stderr, "Server(TLCP) up and listening on port "+port)

			conn, err := ln.Accept()
			if err != nil {
				log.Fatal(err)
			}
			defer ln.Close()

			tlcpcon := conn.(*tlcp.Conn)
			err = tlcpcon.Handshake()
			if err != nil {
				log.Fatalf("server: handshake failed: %s", err)
			} else {
				log.Print("server: conn: Handshake completed")
			}

			state := tlcpcon.ConnectionState()
		
			for _, v := range state.PeerCertificates {
				derBytes, err := smx509.MarshalPKIXPublicKey(v.PublicKey)
				if err != nil {
					log.Fatal(err)
				}
				pubPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: derBytes})
				fmt.Printf("%s\n", pubPEM)
			}

			go handleConnection(conn)
			fmt.Println("Connection accepted")

			for {
				message, err := bufio.NewReader(conn).ReadString('\n')
				if err != nil {
					fmt.Println(err)
					os.Exit(3)
				}
				fmt.Print("Client response: " + string(message))

				reader := bufio.NewReader(os.Stdin)
				fmt.Print("Text to be sent: ")
				text, err := reader.ReadString('\n')
				if err != nil {
					fmt.Println(err)
					os.Exit(3)
				}
				fmt.Fprintf(conn, text+"\n")
			}
		}

		if *tcpip == "client" {
			var cert tlcp.Certificate
			cert, err = tlcp.X509KeyPair(certPEM, privPEM)
			cfg := tlcp.Config{Certificates: []tlcp.Certificate{cert}, InsecureSkipVerify: true, CipherSuites: []uint16{tlcp.ECC_SM4_GCM_SM3}}

			ipport := "127.0.0.1:8081"
			if *iport != "" {
				ipport = *iport
			}

			conn, err := tlcp.Dial("tcp", ipport, &cfg)
			if err != nil {
				log.Fatal(err)
			}
			certs := conn.ConnectionState().PeerCertificates
			for _, cert := range certs {
				fmt.Printf("Issuer: \n\t%s\n", cert.Issuer)
				fmt.Printf("Subject: \n\t%s\n", cert.Subject)
				fmt.Printf("Expiry: %s \n", cert.NotAfter.Format("Monday, 02-Jan-06 15:04:05 MST"))
			}
			if err != nil {
				log.Fatal(err)
			}
			defer conn.Close()

			var b bytes.Buffer
			for _, cert := range conn.ConnectionState().PeerCertificates {
				err := pem.Encode(&b, &pem.Block{
					Type: "CERTIFICATE",
					Bytes: cert.Raw,
			        })
				if err != nil {
					log.Fatal(err)
				}
			}
			fmt.Println(b.String())

			for {
				reader := bufio.NewReader(os.Stdin)
				fmt.Print("Text to be sent: ")
				text, err := reader.ReadString('\n')
				if err != nil {
					fmt.Println(err)
					os.Exit(3)
				}
				fmt.Fprintf(conn, text+"\n")

				message, err := bufio.NewReader(conn).ReadString('\n')
				if err != nil {
					fmt.Println(err)
					os.Exit(3)
				}
				fmt.Print("Server response: " + message)
			}
		}
		os.Exit(0)
	}
}
```

I don't understand what's wrong, if anyone can help me that would be great.

Thanks in advance.

**Comment by pedroalbanese** [comment]
After some tests I realized that it's working, but only with the example certificates, it doesn't work with the certificates generated by my tool EDGETk although it also uses the gmsm library. I can't generate TLCP compliant certificates using my program, and I can't parse the private keys in the library examples either.

**Comment by emmansun** [comment]
1. To support SM2 private key with RFC 5915 / SEC1 format, i will enhance gotlcp.
2. To verify client certificate, pls make sure **ClientCAs** are ready, your server system will NOT support **SM2**. BTW, please make sure you used correct client side certificates (KeyUsage):
```golang
		keyUsages := []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth, x509.ExtKeyUsageServerAuth}
		if c.config.ClientAuth == RequireAndVerifyAnyKeyUsageClientCert {
			keyUsages = []x509.ExtKeyUsage{x509.ExtKeyUsageAny}
		}
```

**Comment by emmansun** [comment]
BTW, suggest you to test the case **InsecureSkipVerify = false** (InsecureSkipVerify 's default value is false), to verify server certificates first.

**Comment by pedroalbanese** [comment]
Very thanks for the tips and I was doing a few things wrong besides that:
1. I was using a non-self-signed certificate as ClientCA.
2. I was generating certificates whose Extended Key Usage was Client Authentication only.

I think an extra flag is needed in my program to define the ROOT_CERT_PEM. But I don't understand if it's imperative that the server uses two pairs of keys. From what I could understand it would be less secure to use the same key to sign and encrypt, but I don't understand if this is a rule. What are the implications of using just one key/certificate pair on the server side?

I mean, otherwise I would need to make more changes to flags like secondary key and secondary certificate. Is it possible to use only one pair of keys or is this contraindicated?

**Comment by emmansun** [comment]
@pedroalbanese , in general, tlcp server will use two pairs of keys: one for sign , another for encryption, they are different keys and generated by same CA, that's also the main reason why tlcp is incompatible with tls. If tlcp client supports ECDHE_SM4_CBC_SM3/ECDHE_SM4_GCM_SM3 suites, it also needs two pairs of keys.

In fact, the real certificates request procedure like below:

1. applicant generates one key pair, and one CSR, sends CSR to CA;
2. CA generates the sign certificate according the CSR, and also generates one key pair, generates one new CSR (use the requestor's CSR as template source), and then generates the encryption certificate.
3. CA returns sign certificate, encryption certificate and encryption private key to applicant. (so, CA keeps your encryption private key)

"What are the implications of using just one key/certificate pair on the server side?", for demo and self-test, it's ok, but you will fail to integrate with others,

**Comment by pedroalbanese** [comment]
That's cool! Quite interesting, I will think about how to deal with the flags, for example keeping a single flag and passing two values separated by semicolons. Thank you so much again for your patience and all the information. It is an honor to be able to learn about China's industrial standard.

**Comment by pedroalbanese** [comment]
Hello again (I didn't want to open a new issue);

I'm having problems with the integration with GmSSL. When I try one-way authentication, it works. But when I try two-way authentication, I get the server error (EDGETk) "server: handshake failed: remote error: tlcp: unsupported certificate", about the client certificate (GmSSL).

I am generating the certificate like this:
gmssl certgen -key sm2priv.pem -pass secret -CN Applicant -key_usage digitalSignature -key_usage nonRepudiation -key_usage keyEncipherment -days 365 -ext_key_usage clientAuth -ext_key_usage serverAuth -out sm2cert.pem

But it results in "unsupported certificate" on the server side.

-----BEGIN CERTIFICATE-----
MIIBUzCB+qADAgECAg0ApKf1vYJPqL+vz9xiMAoGCCqBHM9VAYN1MBQxEjAQBgNV
BAMTCUFwcGxpY2FudDAeFw0yMzEwMjYxNTQ2NTRaFw0yNDEwMjUxNTQ2NTRaMBQx
EjAQBgNVBAMTCUFwcGxpY2FudDBZMBMGByqGSM49AgEGCCqBHM9VAYItA0IABAcO
p6tMBTQSpKEzpFl7uloSvDaQ+6As2DTUEfkZs4f/tLZl7Tw1klafGxcTr49UEByy
nVuv1QqnQZk63kop48GjMTAvMA4GA1UdDwEB/wQEAwIF4DAdBgNVHSUEFjAUBggr
BgEFBQcDAgYIKwYBBQUHAwEwCgYIKoEcz1UBg3UDSAAwRQIgehH1sVhp3Y6qUamJ
IxCZXnPGukw5nhIap43vbredqw0CIQD6unH89Cgx6ZfjFxbjbGahSyUSLbVS4YcB
hAY8uq+LJQ==
-----END CERTIFICATE-----

What I'm doing wrong?

**Comment by emmansun** [comment]
What's the server side detail log and what's your client config?

**Comment by pedroalbanese** [comment]
I was getting this error yesterday, I don't know why, but when I tried to reproduce it today to print the error, the protocol worked. I was doing something wrong yesterday and it mysteriously worked today. Finally, EDGETk is now fully compatible with GmSSL!

![TLCP2](https://github.com/guanzhi/GmSSL/assets/68971450/689ac6fb-7d32-40a9-9a25-abbf79f15b69)

Thank you for your patience and genius libraries! Thank you and Trisia.
