### ISSUE TITLE
单向认证时client异常

### ISSUE THREAD

**Issue by zhangyongding** [Trisia/gotlcp#17]
单向认证时，客户端没有配置证书，如果服务端要求客户端上送证书，会panic

handshake_client.go文件的373行

panic：runtim error: index out of range [0] with length 0

**Comment by emmansun** [comment]
应该是支持ecdhe时引入的一个bug。

**Comment by emmansun** [comment]
@Trisia 这种情况下，服务端报tlcp: client didn't provide a certificate；客户端报remote error: tlcp: bad certificate，是期待的结果吗？
```
--- FAIL: Test_clientHandshake_client_noauth_nocert (3.40s)
    handshake_client_test.go:126: tlcp: client didn't provide a certificate
    handshake_client_test.go:206: remote error: tlcp: bad certificate
FAIL
```

**Comment by Trisia** [comment]
我认为没有什么问题，测了一下确实是Panic的比较严重，我将发布1.3.4版本修复该问题。
