### ISSUE TITLE
ConfirmResponder和RepondKeyExchange返回的切片内容为签名，如果选择不生成签名，则为nil

### ISSUE THREAD

**Issue by emmansun** [Trisia/gotlcp#2]
https://github.com/Trisia/gotlcp/blob/06c153c005bf63011db83e7b4c55ca17ec19e885/tlcp/key_schedule.go#L60
https://github.com/Trisia/gotlcp/blob/06c153c005bf63011db83e7b4c55ca17ec19e885/tlcp/key_schedule.go#L69

shared key需要调用GetSharedKey()方法获取。

**Comment by Trisia** [comment]
确实，疏忽了直接调用了，目前套件还没有测试所以一直没注意。
