### ISSUE TITLE
Doubt about Cipher Suites

### ISSUE THREAD

**Issue by pedroalbanese** [Trisia/gotlcp#21]
Greetings!

I was reading about the cipher suites, which include RSA_SM4_GCM_SM3 and RSA_SM4_GCM_SHA256, but I didn't understand how this happens. I can't use RSA keys to perform the handshake:

`handshake failed: tlcp: no cipher suite supported by both client and server`

Does the library accept other algorithms or is it restricted to SM2 (the only one that works)?

Thank you in advance.

**Comment by Trisia** [comment]
Cipher suites:

- ECC_SM4_GCM_SM3
- ECC_SM4_CBC_SM3
- ECDHE_SM4_GCM_SM3
- ECDHE_SM4_CBC_SM3

are now supportedare currently supported

Where you use RSA, then using the TLS protocol enables greater compatibility.

**Comment by pedroalbanese** [comment]
Thank You!
