### ISSUE TITLE
单向目认证时候，certificate signed by unknown authority错误，请问如何解决。

### ISSUE THREAD

**Issue by blueskydata** [Trisia/gotlcp#25]
程序如下：
func main() {

	//加载根证书
	certBytes, err := os.ReadFile("ca.crt")
	if err != nil {
		panic(err)
	}

	rootCert, err := smx509.ParseCertificatePEM(certBytes)
	if err != nil {
		panic(err)
	}

	pool := smx509.NewCertPool()
	pool.AddCert(rootCert)

	config := &tlcp.Config{RootCAs: pool}
	conn, err := tlcp.Dial("tcp", "127.0.0.1:8443", config)
	if err != nil {
		panic(err)
	}

	buff := make([]byte, 512)
	var str string
	for {
		fmt.Scanln(&str)
		if str == "" {
			break
		}
		_, err = conn.Write([]byte(str))
		if err != nil {
			panic(err)
		}
		n, err := conn.Read(buff)
		if err != nil {
			panic(err)
		}
		fmt.Println("收到消息:", string(buff[:n]))
	}
	conn.Close()
	fmt.Println("bye bye")
}
1、 CA使用了自签名的证书（ca.crt)，存放于/usr/local/share/ca-certificates
2、编译上述程序，并在可执行文件统计目录，也放了根证书（ca.crt)
运行时报如下的错误，请问如何解决，谢谢！
 tlcp: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "jsca.org")

**Comment by emmansun** [comment]
请参考https://github.com/Trisia/gotlcp/blob/main/doc/ClientConfig.md

服务端证书是你这个CA签发的吗？单向认证是客户端验证服务端的证书。

**Comment by blueskydata** [comment]
> 请参考https://github.com/Trisia/gotlcp/blob/main/doc/ClientConfig.md
> 
> 服务端证书是你这个CA签发的吗？单向认证是客户端验证服务端的证书。
是这个CA签发的，这个CA的证书是自签名的，所谓的“jsca.org”是自己填写的。

**Comment by emmansun** [comment]
那请你提供一下所有证书。

**Comment by blueskydata** [comment]
> 那请你提供一下所有证书。
这是ca证书的内容，恳请您指点，谢谢！
 tbsCertificate
        version: v3 (2)
        serialNumber: 448FC4F167D2BDCA1C71F4E3
        signature
            algorithm: sm2sign-with-sm3
        issuer
            countryName: cn
            stateOrProvinceName: js
            localityName: nj
            organizationName: jsca
            organizationalUnitName: jsca-issuer
            commonName: jsca.com
        validity
            notBefore: Mon Sep 16 10:15:06 2024
            notAfter: Thu Sep 14 10:15:06 2034
        subject
            countryName: cn
            stateOrProvinceName: js
            localityName: nj
            organizationName: jsca
            organizationalUnitName: jsca-issuer
            commonName: jsca.com
        subjectPulbicKeyInfo
            algorithm
                algorithm: ecPublicKey
                namedCurve: sm2p256v1
            subjectPublicKey
                ECPoint: 04E532F6F5902242DE9C3713E55C7DD728AD7544FBB8C4434A708AD7B6AC39066206F4BCCB46897878B23367081D8E170915DF365C066BD715050978EE54948102
        extensions
            Extension
                extnID: KeyUsage (2.5.29.15)
                critical: true
                KeyUsage: keyCertSign
    signatureAlgorithm
        algorithm: sm2sign-with-sm3
    signatureValue: 304502205263150AD2590B02A8267A6A3C219ED941F119446B534B12A52A6479B7D5DC2C022100CC45EE79F84FF043BF7C4A310359463B3C7257DDF75633C3BAC3772EF4D89DD3
-----BEGIN CERTIFICATE-----
MIIByjCCAXCgAwIBAgIMRI/E8WfSvcoccfTjMAoGCCqBHM9VAYN1MF8xCzAJBgNV
BAYTAmNuMQswCQYDVQQIEwJqczELMAkGA1UEBxMCbmoxDTALBgNVBAoTBGpzY2Ex
FDASBgNVBAsTC2pzY2EtaXNzdWVyMREwDwYDVQQDEwhqc2NhLmNvbTAeFw0yNDA5
MTYwMjE1MDZaFw0zNDA5MTQwMjE1MDZaMF8xCzAJBgNVBAYTAmNuMQswCQYDVQQI
EwJqczELMAkGA1UEBxMCbmoxDTALBgNVBAoTBGpzY2ExFDASBgNVBAsTC2pzY2Et
aXNzdWVyMREwDwYDVQQDEwhqc2NhLmNvbTBZMBMGByqGSM49AgEGCCqBHM9VAYIt
A0IABOUy9vWQIkLenDcT5Vx91yitdUT7uMRDSnCK17asOQZiBvS8y0aJeHiyM2cI
HY4XCRXfNlwGa9cVBQl47lSUgQKjEjAQMA4GA1UdDwEB/wQEAwICBDAKBggqgRzP
VQGDdQNIADBFAiBSYxUK0lkLAqgmemo8IZ7ZQfEZRGtTSxKlKmR5t9XcLAIhAMxF
7nn4T/BDv3xKMQNZRjs8clfd91Yzw7rDdy702J3T
-----END CERTIFICATE-----

签名证书：
Certificate
    tbsCertificate
        version: v3 (2)
        serialNumber: DD90504B4E589BB5BAD9F656
        signature
            algorithm: sm2sign-with-sm3
        issuer
            countryName: cn
            stateOrProvinceName: js
            localityName: nj
            organizationName: jsca
            organizationalUnitName: jsca-issuer
            commonName: jsca.com
        validity
            notBefore: Mon Sep 16 10:19:27 2024
            notAfter: Thu Sep 14 10:19:27 2034
        subject
            countryName: cn
            stateOrProvinceName: js
            localityName: nj
            organizationName: bluesky
            organizationalUnitName: bluesky-office
            commonName: bluesky.com
        subjectPulbicKeyInfo
            algorithm
                algorithm: ecPublicKey
                namedCurve: sm2p256v1
            subjectPublicKey
                ECPoint: 047A3137DA5DE3D6C1BBD7A5AC7E7525E9CB58357CA1229B8B0227B6F352FBD74A6CB6B497D752D3896942920252AACBC76A5233F6AF0C810C12AAA5EE4F2E7731
        extensions
            Extension
                extnID: KeyUsage (2.5.29.15)
                critical: true
                KeyUsage: digitalSignature
    signatureAlgorithm
        algorithm: sm2sign-with-sm3
    signatureValue: 304502200A508A9139072201076CF04D660735FCF621CDB34A7729A768C6F62C02ACAEA3022100D89222F342E78A49F7A446D897551DA52AAC6AC6D69A0DCD2E1E0D624971E6CC
-----BEGIN CERTIFICATE-----
MIIB1DCCAXqgAwIBAgINAN2QUEtOWJu1utn2VjAKBggqgRzPVQGDdTBfMQswCQYD
VQQGEwJjbjELMAkGA1UECBMCanMxCzAJBgNVBAcTAm5qMQ0wCwYDVQQKEwRqc2Nh
MRQwEgYDVQQLEwtqc2NhLWlzc3VlcjERMA8GA1UEAxMIanNjYS5jb20wHhcNMjQw
OTE2MDIxOTI3WhcNMzQwOTE0MDIxOTI3WjBoMQswCQYDVQQGEwJjbjELMAkGA1UE
CBMCanMxCzAJBgNVBAcTAm5qMRAwDgYDVQQKEwdibHVlc2t5MRcwFQYDVQQLEw5i
bHVlc2t5LW9mZmljZTEUMBIGA1UEAxMLYmx1ZXNreS5jb20wWTATBgcqhkjOPQIB
BggqgRzPVQGCLQNCAAR6MTfaXePWwbvXpax+dSXpy1g1fKEim4sCJ7bzUvvXSmy2
tJfXUtOJaUKSAlKqy8dqUjP2rwyBDBKqpe5PLncxoxIwEDAOBgNVHQ8BAf8EBAMC
B4AwCgYIKoEcz1UBg3UDSAAwRQIgClCKkTkHIgEHbPBNZgc1/PYhzbNKdymnaMb2
LAKsrqMCIQDYkiLzQueKSfekRtiXVR2lKqxqxtaaDc0uHg1iSXHmzA==
-----END CERTIFICATE-----
加密证书：
Certificate
    tbsCertificate
        version: v3 (2)
        serialNumber: 0772930D7B330DA1D8DA8A09
        signature
            algorithm: sm2sign-with-sm3
        issuer
            countryName: cn
            stateOrProvinceName: js
            localityName: nj
            organizationName: jsca
            organizationalUnitName: jsca-issuer
            commonName: jsca.com
        validity
            notBefore: Mon Sep 16 10:22:48 2024
            notAfter: Thu Sep 14 10:22:48 2034
        subject
            countryName: cn
            stateOrProvinceName: st
            localityName: nj
            organizationName: bluesky
            organizationalUnitName: bluesky-office
            commonName: bluesky.com
        subjectPulbicKeyInfo
            algorithm
                algorithm: ecPublicKey
                namedCurve: sm2p256v1
            subjectPublicKey
                ECPoint: 04FBF4D04C9D90A39D52D4BD28302449D152B816FB48BA1A5C288219A77A2360954A4BA02EFEBD92637435BF20241880F305BBB939CD50946D1E6A3388F98CF309
        extensions
            Extension
                extnID: KeyUsage (2.5.29.15)
                critical: true
                KeyUsage: keyEncipherment
    signatureAlgorithm
        algorithm: sm2sign-with-sm3
    signatureValue: 304502206C72407EB5039C1E5339C7C04F9C28E72C1D831BAAF6FEE76132323BBDBB187B022100FC01B114E98F108B63842202B0B6B10DE9E4E807A47B51155CA16BBAB45898BC
-----BEGIN CERTIFICATE-----
MIIB0zCCAXmgAwIBAgIMB3KTDXszDaHY2ooJMAoGCCqBHM9VAYN1MF8xCzAJBgNV
BAYTAmNuMQswCQYDVQQIEwJqczELMAkGA1UEBxMCbmoxDTALBgNVBAoTBGpzY2Ex
FDASBgNVBAsTC2pzY2EtaXNzdWVyMREwDwYDVQQDEwhqc2NhLmNvbTAeFw0yNDA5
MTYwMjIyNDhaFw0zNDA5MTQwMjIyNDhaMGgxCzAJBgNVBAYTAmNuMQswCQYDVQQI
EwJzdDELMAkGA1UEBxMCbmoxEDAOBgNVBAoTB2JsdWVza3kxFzAVBgNVBAsTDmJs
dWVza3ktb2ZmaWNlMRQwEgYDVQQDEwtibHVlc2t5LmNvbTBZMBMGByqGSM49AgEG
CCqBHM9VAYItA0IABPv00EydkKOdUtS9KDAkSdFSuBb7SLoaXCiCGad6I2CVSkug
Lv69kmN0Nb8gJBiA8wW7uTnNUJRtHmoziPmM8wmjEjAQMA4GA1UdDwEB/wQEAwIF
IDAKBggqgRzPVQGDdQNIADBFAiBsckB+tQOcHlM5x8BPnCjnLB2DG6r2/udhMjI7
vbsYewIhAPwBsRTpjxCLY4QiArC2sQ3p5OgHpHtRFVyha7q0WJi8
-----END CERTIFICATE-----

**Comment by emmansun** [comment]
你的CA有问题：
```go
	// RFC 5280, 4.2.1.9:
	// "If the basic constraints extension is not present in a version 3
	// certificate, or the extension is present but the cA boolean is not
	// asserted, then the certified public key MUST NOT be used to verify
	// certificate signatures."
	if parent.Version == 3 && !parent.BasicConstraintsValid ||
		parent.BasicConstraintsValid && !parent.IsCA {
		return x509.ConstraintViolationError{}
	}
```
不知道你是怎么生成CA证书的，如果用Golang自己写的，可以参考https://github.com/emmansun/mksmcert/blob/dbff377dc9faff59061aeb48a59f655664a8847f/cert.go#L302

**Comment by blueskydata** [comment]
> 你的CA有问题：
> 
> ```go
> 	// RFC 5280, 4.2.1.9:
> 	// "If the basic constraints extension is not present in a version 3
> 	// certificate, or the extension is present but the cA boolean is not
> 	// asserted, then the certified public key MUST NOT be used to verify
> 	// certificate signatures."
> 	if parent.Version == 3 && !parent.BasicConstraintsValid ||
> 		parent.BasicConstraintsValid && !parent.IsCA {
> 		return x509.ConstraintViolationError{}
> 	}
> ```
> 
> 不知道你是怎么生成CA证书的，如果用Golang自己写的，可以参考https://github.com/emmansun/mksmcert/blob/dbff377dc9faff59061aeb48a59f655664a8847f/cert.go#L302
用gmssl 3.1.1生成的，发现用gmssl certverify命令验证证书都失败，我试试您的看看。

**Comment by emmansun** [comment]
gmssl不是也有个ca参数吗？https://github.com/guanzhi/GmSSL/blob/master/tools/certgen.c

**Comment by blueskydata** [comment]
> 你的CA有问题：
> 
> ```go
> 	// RFC 5280, 4.2.1.9:
> 	// "If the basic constraints extension is not present in a version 3
> 	// certificate, or the extension is present but the cA boolean is not
> 	// asserted, then the certified public key MUST NOT be used to verify
> 	// certificate signatures."
> 	if parent.Version == 3 && !parent.BasicConstraintsValid ||
> 		parent.BasicConstraintsValid && !parent.IsCA {
> 		return x509.ConstraintViolationError{}
> 	}
> ```
> 
> 不知道你是怎么生成CA证书的，如果用Golang自己写的，可以参考https://github.com/emmansun/mksmcert/blob/dbff377dc9faff59061aeb48a59f655664a8847f/cert.go#L302

我使用了您的工具生成了，生成了key和证书，并在windows使用命令mksmcert -install。
在server中的代码如下,其中kaifa是主机名：
cert, err := tlcp.LoadX509KeyPair("kaifa.pem", "kaifa-key.pem")
	config := &tlcp.Config{
		Certificates: []tlcp.Certificate{cert},
	}
	listen, err := tlcp.Listen("tcp", ":8443", config)
	if err != nil {
		panic(err)
	}

在client中的地吗，代码如下：
conn, err := tlcp.Dial("tcp", "127.0.0.1:8443", &tlcp.Config{InsecureSkipVerify: true})
	if err != nil {
		panic(err)
	}
在客户端连 接的时候报错： remote error: tlcp: unrecognized name
此时，服务端报错：tlcp: no certificates configured

证书kaifa.perm的内容：
Certificate
    tbsCertificate
        version: v3 (2)
        serialNumber: 786C502B84FF4C83D3E1E42E20F42854
        signature
            algorithm: sm2sign-with-sm3
        issuer
            organizationName: mksmcert development CA
            organizationalUnitName: KAIFA\lt@kaifa
            commonName: mksmcert KAIFA\lt@kaifa
        validity
            notBefore: Mon Sep 16 15:58:54 2024
            notAfter: Wed Dec 16 15:58:54 2026
        subject
            organizationName: mksmcert development certificate
            organizationalUnitName: KAIFA\lt@kaifa
        subjectPulbicKeyInfo
            algorithm
                algorithm: ecPublicKey
                namedCurve: sm2p256v1
            subjectPublicKey
                ECPoint: 04724DB59EB7DAD1B87E31C8A20D219F35F777AD92D201518E1C91955E36EB44AE01F377094FF1341446412DEA6A953F9822A56DBBB18F805EA9006BB66D587F2C
        extensions
            Extension
                extnID: KeyUsage (2.5.29.15)
                critical: true
                KeyUsage: digitalSignature,keyEncipherment
            Extension
                extnID: ExtKeyUsage (2.5.29.37)
                ExtKeyUsage
                    serverAuth
            Extension
                extnID: AuthorityKeyIdentifier (2.5.29.35)
                AuthorityKeyIdentifier
                    keyIdentifier: 43176A0FC33E714391B382C4E45B7DCE65DE016F
            Extension
                extnID: SubjectAltName (2.5.29.17)
                SubjectAltName
                    GeneralName
                        DNSName: kaifa
    signatureAlgorithm
        algorithm: sm2sign-with-sm3
    signatureValue: 3046022100F1CCDB9941293E522FAEA8FF1CA9F749C40B14E96299C4E92A1B4D2BE563F6C9022100C45785F1A830DE01E7142146CFE98C77C33726B8774735573CE30865A5ACD0B9
-----BEGIN CERTIFICATE-----
MIIB+jCCAZ+gAwIBAgIQeGxQK4T/TIPT4eQuIPQoVDAKBggqgRzPVQGDdTBdMSAw
HgYDVQQKExdta3NtY2VydCBkZXZlbG9wbWVudCBDQTEXMBUGA1UECwwOS0FJRkFc
bHRAa2FpZmExIDAeBgNVBAMMF21rc21jZXJ0IEtBSUZBXGx0QGthaWZhMB4XDTI0
MDkxNjA3NTg1NFoXDTI2MTIxNjA3NTg1NFowRDEpMCcGA1UEChMgbWtzbWNlcnQg
ZGV2ZWxvcG1lbnQgY2VydGlmaWNhdGUxFzAVBgNVBAsMDktBSUZBXGx0QGthaWZh
MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEck21nrfa0bh+MciiDSGfNfd3rZLS
AVGOHJGVXjbrRK4B83cJT/E0FEZBLepqlT+YIqVtu7GPgF6pAGu2bVh/LKNaMFgw
DgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB8GA1UdIwQYMBaA
FEMXag/DPnFDkbOCxORbfc5l3gFvMBAGA1UdEQQJMAeCBWthaWZhMAoGCCqBHM9V
AYN1A0kAMEYCIQDxzNuZQSk+Ui+uqP8cqfdJxAsU6WKZxOkqG00r5WP2yQIhAMRX
hfGoMN4B5xQhRs/pjHfDNya4d0c1VzzjCGWlrNC5
-----END CERTIFICATE-----

rootCA.pem中的内容：
Certificate
    tbsCertificate
        version: v3 (2)
        serialNumber: 12B07C5FDC46115041F3ACD822B1235E
        signature
            algorithm: sm2sign-with-sm3
        issuer
            organizationName: mksmcert development CA
            organizationalUnitName: KAIFA\lt@kaifa
            commonName: mksmcert KAIFA\lt@kaifa
        validity
            notBefore: Mon Sep 16 14:38:59 2024
            notAfter: Sat Sep 16 14:38:59 2034
        subject
            organizationName: mksmcert development CA
            organizationalUnitName: KAIFA\lt@kaifa
            commonName: mksmcert KAIFA\lt@kaifa
        subjectPulbicKeyInfo
            algorithm
                algorithm: ecPublicKey
                namedCurve: sm2p256v1
            subjectPublicKey
                ECPoint: 045CF5130CF89F4653348FA5B9E544CCDE2223B5BEA373A2B406C3C55260CCB9F261215E6B06682BD00C28F4D506647C5CC139AD3099F3E28CE55E2750B8D1BF24
        extensions
            Extension
                extnID: KeyUsage (2.5.29.15)
                critical: true
                KeyUsage: keyCertSign
            Extension
                extnID: BasicConstraints (2.5.29.19)
                critical: true
                BasicConstraints
                    cA: true
                    pathLenConstraint: 0
            Extension
                extnID: SubjectKeyIdentifier (2.5.29.14)
                SubjectKeyIdentifier: 43176A0FC33E714391B382C4E45B7DCE65DE016F
    signatureAlgorithm
        algorithm: sm2sign-with-sm3
    signatureValue: 304502210093A62FD1E7305B8AC23B3C48C3C359978AFE2439ED64B56AC7A791C0E6A72C9102204972A1084840C05840D97B39A0F956E1A257A999FD426460398FC0E239416006
-----BEGIN CERTIFICATE-----
MIIB/TCCAaOgAwIBAgIQErB8X9xGEVBB86zYIrEjXjAKBggqgRzPVQGDdTBdMSAw
HgYDVQQKExdta3NtY2VydCBkZXZlbG9wbWVudCBDQTEXMBUGA1UECwwOS0FJRkFc
bHRAa2FpZmExIDAeBgNVBAMMF21rc21jZXJ0IEtBSUZBXGx0QGthaWZhMB4XDTI0
MDkxNjA2Mzg1OVoXDTM0MDkxNjA2Mzg1OVowXTEgMB4GA1UEChMXbWtzbWNlcnQg
ZGV2ZWxvcG1lbnQgQ0ExFzAVBgNVBAsMDktBSUZBXGx0QGthaWZhMSAwHgYDVQQD
DBdta3NtY2VydCBLQUlGQVxsdEBrYWlmYTBZMBMGByqGSM49AgEGCCqBHM9VAYIt
A0IABFz1Ewz4n0ZTNI+lueVEzN4iI7W+o3OitAbDxVJgzLnyYSFeawZoK9AMKPTV
BmR8XME5rTCZ8+KM5V4nULjRvySjRTBDMA4GA1UdDwEB/wQEAwICBDASBgNVHRMB
Af8ECDAGAQH/AgEAMB0GA1UdDgQWBBRDF2oPwz5xQ5GzgsTkW33OZd4BbzAKBggq
gRzPVQGDdQNIADBFAiEAk6Yv0ecwW4rCOzxIw8NZl4r+JDntZLVqx6eRwOanLJEC
IElyoQhIQMBYQNl7OaD5VuGiV6mZ/UJkYDmPwOI5QWAG
-----END CERTIFICATE-----

**Comment by emmansun** [comment]
tlcp服务端不是需要双证书吗？建议你多看示例代码和文档。

**Comment by blueskydata** [comment]
> tlcp服务端不是需要双证书吗？建议你多看示例代码和文档。
你这个工具只能产生单证书啊
