### ISSUE TITLE
TLCP的ECDHE实现问题

### ISSUE THREAD

**Issue by emmansun** [Trisia/gotlcp#4]
https://github.com/Trisia/gotlcp/blob/9729b48053693d014b5ffb6e5b2ed34f7625920e/tlcp/key_agreement.go#L265

TLCP标准文档相当简约，只说ECDHE实现参考**GB/T 35276**，但是**GB/T 35276**是SM2完整密钥协商的输入、输出定义而已。所以：

1. TLCP交换生成shared secret 或叫预主密钥的过程使用了完整的SM2密钥协商过程。
2. 如果真要使用SM2密钥协商过程来交换生成预主密钥，却不对相关参数给出规定。

这样的话，怎么验证实现的正确性？不同的实现如何能互操作？

**Comment by Trisia** [comment]
该问题我也比较困扰，从目前公布资料上来看我并没有找到可以贴合的文献关于该部分的详细描述，按照RFC的习惯这类标准都会存在补充说明的系列文献，但是我也尝试去GM/T 与GB/T 去寻找，均为找到相关文献。

目前实现的这一版ECDHE都是我多方资料拼凑实现的，还有很多的细节上的东西其实我也是无能为力，我也曾尝试在 gmssl项目中寻找答案，而gmssl目前也是只实现了 ECC_SM4_CBC_SM3。

**Comment by Trisia** [comment]
在 《GBT 36322-2018 信息安全技术 密码设备应用接口规范》（SDF）中有关于ECDHE一点点的描述但是没有太大价值。

**Comment by emmansun** [comment]
不知道阿里的[BaBaSSL](https://github.com/Tongsuo-Project/Tongsuo)的实现有没有经过认证。

**Comment by emmansun** [comment]
https://github.com/Tongsuo-Project/Tongsuo/issues/196 BaBaSSL也有类似的问题

**Comment by Trisia** [comment]
我到觉得这个问题，通过去看代码这种方式不是很好的解决方案，要彻底解决该问题只能是更加详细的协议设计文档，目前由于没有这类文档，该问题只能搁置了...

**Comment by emmansun** [comment]
> 我到觉得这个问题，通过去看代码这种方式不是很好的解决方案，要彻底解决该问题只能是更加详细的协议设计文档，目前由于没有这类文档，该问题只能搁置了...

同意

**Comment by emmansun** [comment]
@Trisia 我通过以下修改，客户端实现可以与[gmssl](https://demo.gmssl.cn:1443)进行ECDHE互操作了：

1. 客户端使用双密钥：一个签名密钥，一个加密密钥。
2. 修改sm2ECDHEKeyAgreement的方法generateClientKeyExchange()
![image](https://user-images.githubusercontent.com/7235232/219314009-3a0c755b-44db-42bc-8866-db427298dcd2.png)

**关于第二点，您能确认一下哪个实现是正确的吗？**

**Comment by xuyang2** [comment]
> 不知道阿里的[BaBaSSL](https://github.com/Tongsuo-Project/Tongsuo)的实现有没有经过认证。

“截止 2023 年 1 月底，铜锁密码库一共取得了国家密码管理局商用密码检测中心颁发的三个商用密码产品认证证书，也即俗称的国密资质。这三个资质均属于 GM/T 0028《密码模块安全技术要求》安全一级。”

- https://www.yuque.com/tsdoc/misc/st247r05s8b5dtct
- https://mp.weixin.qq.com/s/9zzK4ZR9OEw4e-wskkGD9w

**Comment by emmansun** [comment]
我的意思是ECDHEParams前面要不要加两字节长度？

**Comment by emmansun** [comment]
我看了golang SDK的ECDHE [ecdheKeyAgreement.generateServerKeyExchange](https://github.com/golang/go/blob/031401a7905a38498fc399fc10cd0c1e885f7fc9/src/crypto/tls/key_agreement.go#L169)，应该是不需要的。

**Comment by emmansun** [comment]
改了一版，https://github.com/emmansun/gotlcp/commit/f841987cbf58b8221ce7cda0c902bad4fe3a9679， 服务端需要更多测试。要是能把测试和GITHUB ACTION集成起来就好了。

**Comment by Trisia** [comment]
好的，我将合并您的请求。

**Comment by Trisia** [comment]
请问 能否简要的描述一下客户端使用客户端与服务端进行ECDHE的细节，流程之类的，以及交换消息的数据结构？我方便编写文档

**Comment by Trisia** [comment]
> @Trisia 我通过以下修改，客户端实现可以与[gmssl](https://demo.gmssl.cn:1443)进行ECDHE互操作了：
> 
> 1. 客户端使用双密钥：一个签名密钥，一个加密密钥。
> 2. 修改sm2ECDHEKeyAgreement的方法generateClientKeyExchange()
>    ![image](https://user-images.githubusercontent.com/7235232/219314009-3a0c755b-44db-42bc-8866-db427298dcd2.png)
> 
> **关于第二点，您能确认一下哪个实现是正确的吗？**

我看了go的`generateClientKeyExchange` 确实只是使用了 这个结构
```
		struct {
			ECParameters    curve_params;
			ECPoint         public;
		} ClientECDHParams;
```

而不是

```
opaque ClientECDHEParams<1..2^16-1>;
```

这部分我也难以判断，很有可能需要结合实践经验来调整了，可以先兼容。

**Comment by emmansun** [comment]
这个服务器端应该可以做到自适应，客户端可能需要配置选项。

**Comment by emmansun** [comment]
> @emmansun 请问 能否简要的描述一下客户端使用客户端与服务端进行ECDHE的细节与交换流程？

其实流程没有改变，主要是：
1.客户端如果要支持sm2 ecdhe，那么就和服务器端一样，需要配置双密码对。
2.就是clientECDHEParametet的处理问题。

**Comment by Trisia** [comment]
> 这个服务器端应该可以做到自适应，客户端可能需要配置选项。

嗯，这样确实不错！

**Comment by Trisia** [comment]
> > @emmansun 请问 能否简要的描述一下客户端使用客户端与服务端进行ECDHE的细节与交换流程？
> 
> 其实流程没有改变，主要是： 1.客户端如果要支持sm2 ecdhe，那么就和服务器端一样，需要配置双密钥对。双方都使用加密密钥对进行key exchange。 2.就是clientECDHEParameter的处理问题。

了解。

**Comment by emmansun** [comment]
看了Tongsuo的代码，也没有处理成可变长度Vector。
	https://github.com/Tongsuo-Project/Tongsuo/blob/c5951fef1232f6fa731f8857ef270fe86fa8961e/ssl/statem_ntls/ntls_statem_srvr.c#L2024
	https://github.com/Tongsuo-Project/Tongsuo/blob/c5951fef1232f6fa731f8857ef270fe86fa8961e/ssl/statem_ntls/ntls_statem_srvr.c#L1945

```c
static int tls_process_cke_sm2dhe_ntls(SSL *s, PACKET *pkt)
{
    const unsigned char *ecparams;
    EVP_PKEY *skey = s->s3.tmp.pkey;
    EVP_PKEY *ckey = NULL;
    int ret = 0;

    if (PACKET_remaining(pkt) == 0L) {
        /* We don't support ECDH client auth */
        SSLfatal_ntls(s, SSL_AD_HANDSHAKE_FAILURE, SSL_R_MISSING_TMP_ECDH_KEY);
        goto err;
    } else {
        unsigned int i;
        const unsigned char *data;

        /*
         * Get client's public key from encoded point in the
         * ClientKeyExchange message.
         */

        if (!PACKET_get_bytes(pkt, &ecparams, 3)) {
            SSLfatal_ntls(s, SSL_AD_DECODE_ERROR, SSL_R_LENGTH_TOO_SHORT);
            goto err;
        }

        /* Get encoded point length */
        if (!PACKET_get_1(pkt, &i) || !PACKET_get_bytes(pkt, &data, i)
            || PACKET_remaining(pkt) != 0) {
            SSLfatal(s, SSL_AD_DECODE_ERROR, SSL_R_LENGTH_MISMATCH);
            goto err;
        }
...
```

**Comment by Trisia** [comment]
确实是这样的，这里我个人认为您提供的开关已经足够了，将合并您的请求并发布新的版本 v1.3.0

**Comment by Trisia** [comment]
#15
