### ISSUE TITLE
是否可以考虑自适应支持tlcp和标准的tls

### ISSUE THREAD

**Issue by zhangyongding** [Trisia/gotlcp#5]
是否可以实现github.com/tjfoc/gmsm/gmtls中类似自适应支持tlcp和标准tls的功能

**Comment by Trisia** [comment]
不考虑，加入了tls之后会使项目难以维护。

**Comment by zhangyongding** [comment]
不是说这个项目支持标准的tls，而是说这个项目支持同一个地址支持绑定tlcp和tls，tls还是使用go的标准库

**Comment by zhangyongding** [comment]
谢谢，我找到其他的方法来实现一个地址绑定tlcp和tls了。
[https://github.com/soheilhy/cmux](url)

**Comment by Trisia** [comment]
该特性已经于 GoTLCP v1.2.0 实现，欢迎体验！

**Comment by Trisia** [comment]
> 谢谢，我找到其他的方法来实现一个地址绑定tlcp和tls了。 [https://github.com/soheilhy/cmux](url)

你也可以向example中共享您的解决方案。

**Comment by xuyang2** [comment]
> 该特性已经于 GoTLCP v1.2.0 实现，欢迎体验！

ProtocolDetectConn 的代码是否可以用 bufio.Reader 简化一下
https://stackoverflow.com/questions/26196813/peek-into-conn-without-reading-in-go

**Comment by Trisia** [comment]
由于`ProtocolDetectConn ` 只对连接的头5byte检测，因此不需要缓冲，缓冲区可能会对上层的应用造成一定影响。
