### ISSUE TITLE
除了签名、加密证书，发送证书链到客户端

### ISSUE THREAD

**Issue by emmansun** [Trisia/gotlcp#8]
考虑到国密双证书应该拥有一样的证书链（申请国密证书时，客户发送CSR给CA，CA签发证书给客户，包含签名证书、加密证书和加密私钥）。

因为本实现分开了签名、加密证书配置，所以服务端先检查签名证书是否包含证书链，如有，则附加到加密证书之后；否则检查加密证书是否包含证书链，如有，则附加到加密证书之后。

**Comment by Trisia** [comment]
预计与 1.1.3 发布
